"""On-device enrichment: callsign prefix -> airline name + badge (issue #2: no cloud).

A flight callsign is a 3-letter ICAO operator designator followed by the flight
number: "SWA1234" -> "SWA" -> Southwest. AIRLINES is a small curated table of
carriers commonly seen over the US (mainline, regional, cargo, a few
fractional/foreign). Badges are generic letter-mark tiles (DESIGN.md sec. 2: no
airline trademark artwork) generated by tools/gen_badges.py into
lib/logos/<key>.bmp, where <key> is the lowercase ICAO designator.

The "mark" is the IATA code where one exists (what passengers see on a
departure board), else the ICAO designator. Colors are arbitrary, picked to be
distinct and legible on the LED panel; they are not brand colors.

CircuitPython-safe: no f-strings, no typing, no re.
"""

LOGO_DIR = "/lib/logos"
UNKNOWN_KEY = "_unk"   # generic fallback badge: lib/logos/_unk.bmp

# ICAO designator: (display name <= 16 chars, badge mark 2-3 chars, badge bg 0xRRGGBB)
AIRLINES = {
    # US mainline / low-cost
    "AAL": ("American", "AA", 0x0078D2),
    "DAL": ("Delta", "DL", 0xC01933),
    "UAL": ("United", "UA", 0x005DAA),
    "SWA": ("Southwest", "WN", 0xF9B612),
    "ASA": ("Alaska", "AS", 0x00A8E0),
    "JBU": ("JetBlue", "B6", 0x0033A0),
    "NKS": ("Spirit", "NK", 0xFFEC00),
    "FFT": ("Frontier", "F9", 0x00843D),
    "AAY": ("Allegiant", "G4", 0xF58025),
    "HAL": ("Hawaiian", "HA", 0x9B1F83),
    "SCX": ("Sun Country", "SY", 0xF26B21),
    "VXP": ("Avelo", "XP", 0x6C2C91),
    "MXY": ("Breeze", "MX", 0x00A3E0),
    # US regionals (fly as American Eagle / Delta Connection / United Express)
    "SKW": ("SkyWest", "OO", 0x2F5DA8),
    "ENY": ("Envoy", "MQ", 0x5A6C7A),
    "RPA": ("Republic", "YX", 0x1F4E9A),
    "EDV": ("Endeavor", "9E", 0xB22234),
    "JIA": ("PSA", "OH", 0x3A77C9),
    "ASH": ("Mesa", "YV", 0xC9A227),
    "QXE": ("Horizon", "QX", 0x2A7AB0),
    "PDT": ("Piedmont", "PT", 0x4F7FB8),
    "GJS": ("GoJet", "G7", 0x2D6FB5),
    "AWI": ("Air Wisconsin", "ZW", 0x2E8B57),
    "UCA": ("CommutAir", "C5", 0x0E7C86),
    "KAP": ("Cape Air", "9K", 0x3C8D2F),
    # US cargo / charter
    "FDX": ("FedEx", "FX", 0x4D148C),
    "UPS": ("UPS", "5X", 0x8B5E3C),
    "GTI": ("Atlas Air", "5Y", 0x1B4F9C),
    "ABX": ("ABX Air", "GB", 0x2B5FAA),
    "ATN": ("ATI", "8C", 0x1F6FB2),
    "CKS": ("Kalitta", "K4", 0xD2232A),
    "PAC": ("Polar", "PO", 0x2A9FD6),
    "AJT": ("Amerijet", "M6", 0xE35205),
    "OAE": ("Omni Air", "OY", 0x16508C),
    "NCR": ("National", "N8", 0x1C3F94),
    # Fractional / business operators (operator callsigns, not tail numbers)
    "EJA": ("NetJets", "1I", 0x7A7A7A),
    "LXJ": ("Flexjet", "LXJ", 0x4A4A4A),
    # Canada / Mexico
    "ACA": ("Air Canada", "AC", 0xD22630),
    "WJA": ("WestJet", "WS", 0x00A1A8),
    "AMX": ("Aeromexico", "AM", 0x1E4E9C),
    "VIV": ("Viva Aerobus", "VB", 0x00A94F),
    "VOI": ("Volaris", "Y4", 0x7B2D8E),
    # Long-haul foreign carriers common at US hubs (IAH, DFW, ...)
    "BAW": ("British Airways", "BA", 0x2E5C99),
    "DLH": ("Lufthansa", "LH", 0xF9B000),
    "KLM": ("KLM", "KL", 0x00A1DE),
    "AFR": ("Air France", "AF", 0x1F4AA0),
    "UAE": ("Emirates", "EK", 0xD71921),
    "QTR": ("Qatar", "QR", 0x8A1538),
    "THY": ("Turkish", "TK", 0xC70A0C),
}


def prefix(callsign):
    """Operator designator of an airline-style callsign, or None.

    "SWA1234 " -> "SWA", "ual2" -> "UAL", "N123AB" -> None (US tail number),
    "" / None -> None. Needs 3 letters then a digit (flight number), which
    also rejects registrations like "CGABC" or "XAABC".
    """
    if not callsign:
        return None
    cs = callsign.strip().upper()
    if len(cs) < 4:
        return None
    p = cs[:3]
    if not p.isalpha() or not cs[3].isdigit():
        return None
    return p


def lookup(callsign):
    """Raw callsign -> (airline_name, badge_key) or None if not in AIRLINES."""
    p = prefix(callsign)
    if p is None:
        return None
    row = AIRLINES.get(p)
    if row is None:
        return None
    return (row[0], p.lower())


def badge_path(badge_key):
    """Path of the badge BMP; None/unknown key -> the generic fallback badge."""
    if badge_key is None or badge_key.upper() not in AIRLINES:
        badge_key = UNKNOWN_KEY
    return LOGO_DIR + "/" + badge_key + ".bmp"
